general:
  python: [
      [ 'scripts/bam2cov',                         'production_bin' ],
      [ 'scripts/bam2snp',                         'production_bin' ],
      [ 'scripts/crawler.py',                      'production_bin' ],
      [ 'scripts/features_with_term_property.py',  'production_bin' ],
      [ 'scripts/genedb_to_uniprot.py',            'production_bin' ],
      [ 'scripts/get_orthologues_filtered.py',     'production_bin' ],
      [ 'scripts/get_synonyms.py',                 'production_bin' ],
      [ 'scripts/gffmini.py',                      'production_bin' ],
      [ 'scripts/run_with_json.py',                'production_bin' ],
      [ 'scripts/wiki_extract.py',                 'production_bin' ],
      [ 'scripts/wiki_load_homepages.py',          'production_bin' ],
      [ 'scripts/writedb_entries.py',              'production_bin' ],
      [ 'scripts/fastn2gc.py',                     'production_bin' ],
      [ 'scripts/mh12_utils.py',                   'production_bin' ],
      [ 'scripts/fastn.py',                        'production_bin' ],
      [ 'scripts/fastn_split.py',                  'production_bin' ],
      [ 'scripts/get_sequencing_project_pages.py', 'production_bin' ],
      [ 'scripts/snp_sites_plink_files.py',        'production_bin' ],
      [ 'scripts/get_annot_changes_list',          'production_bin' ],
      [ 'scripts/push_gffdump_to_ftp.py',          'production_bin' ],
      [ 'modules/wikipy.py',                       'production_lib' ],
      [ 'modules/util',                            'production_lib' ],
      [ 'modules/gffminimal',                      'production_lib' ],
      [ 'modules/ropy',                            'production_lib' ],
      [ 'modules/writedb_entry_set',               'production_lib' ],
      [ 'modules/crawl',                           'production_lib' ],
      [ 'scripts/rm_pathpipe_tmp.py',              'pathdev_bin'],
      [ 'scripts/report_large_files.py',           'pathdev_bin'],
  ]

  perl: [
      ['scripts/reconnect_symlinks_from_nexsan_to_lustre',           'pathdev_bin'],
      ['scripts/EMBL_submission_add_header.pl',                      'pathdev_bin'],
      ['scripts/EMBL_submission_add_source.pl',                      'pathdev_bin'],
      ['scripts/EMBL_submission_add_source_when_none_exist.pl',      'pathdev_bin'],
      ['scripts/EMBL_submission_list_files_with_no_source.pl',       'pathdev_bin'],
      ['scripts/EMBL_submission_rebuild_scaffold_sequence.pl',       'pathdev_bin'],
      ['scripts/EMBL_submission_remove_empty_files.pl',              'pathdev_bin'],
      ['scripts/EMBL_submission_remove_features.pl',                 'pathdev_bin'],
      ['scripts/EMBL_submission_remove_files_with_no_annotation.pl', 'pathdev_bin'],
      ['scripts/EMBL_submission_remove_note.pl',                     'pathdev_bin'],
      ['scripts/EMBL_submission_remove_qualifiers.pl',               'pathdev_bin'],
      ['scripts/EMBL_submission_run_EMBL_validator.pl',              'pathdev_bin'],
      ['scripts/EMBL_submission_summarise_errors.pl',                'pathdev_bin'],
      ['scripts/EMBL_submission_tw_rm_note.pl',                      'pathdev_bin'],
      [ 'scripts/fastq_to_fasta',                                    'production_bin' ],
      [ 'scripts/signalp_chado',                                     'production_bin' ],
      [ 'scripts/merge_rnaseq_expression_spreadsheets.pl',           'pathdev_bin' ],
      [ 'scripts/annotate_references',                               'pathdev_bin' ],
      [ 'scripts/convert_gff3_to_gff2.pl',                           'production_bin' ],
      [ 'scripts/validate_multi_fasta_alignment',                    'production_bin' ],
      [ 'scripts/count_ns_in_alignment',                             'production_bin' ],
      [ 'scripts/pacbio_smrtanalysis',                               'production_bin' ],
      [ 'scripts/exclude_sequences_from_fasta',                      'production_bin' ],
      [ 'scripts/backup_documents.pl',                               'pathdev_bin' ],
      [ 'scripts/populate_organisms.pl',                             'pathdev_bin' ],
      [ 'scripts/rt_report',                                         'pathdev_bin' ],
      [ 'scripts/update_lustre_ref_genomes.pl',                      'pathdev_bin' ],
      [ 'scripts/strip_sequence_from_gff_file.pl',                   'pathdev_bin' ],
      [ 'scripts/check_lustre.pl',                                   'pathdev_bin' ],
      [ 'scripts/fetch_references.pl',                               'pathdev_bin' ],
      [ 'scripts/list_used_references.pl',                           'pathdev_bin' ],
      [ 'scripts/reads_analysis.pl',                                 'pathdev_bin' ],
      [ 'scripts/set_orgprops.pl',                                   'pathdev_bin' ],
      [ 'scripts/check_aux_files.pl',                                'pathdev_bin' ],
      [ 'scripts/num_lanes_in_pipelines',                            'pathdev_bin' ],
      [ 'scripts/forecast_sequencing_data.pl',                       'pathdev_bin' ],
      [ 'scripts/ena_submissions_update.pl',                         'pathdev_bin' ],
      [ 'scripts/generate_project_pages.pl',                         'pathdev_bin' ],
      [ 'scripts/retry_failed_lanes.pl',                             'pathdev_bin' ],
      [ 'scripts/update_species_table.pl',                           'pathdev_bin' ],
      [ 'scripts/scaffold_perl_application.pl',                      'pathdev_bin' ],
      [ 'scripts/create_blast_dbs_from_annotation_pipeline',         'pathdev_bin' ],
      [ 'scripts/rebalance_disks',                                   'pathdev_bin' ],
      [ 'scripts/pacbio_assemble_smrtanalysis',                      'production_bin' ],
      [ 'scripts/identify_protein_changes_at_position',              'production_bin' ],
      [ 'scripts/whereismydata',                                     'production_bin' ],
      [ 'scripts/extract_region_from_multifasta',                    'production_bin' ],
      [ 'scripts/submission_lookup',                                 'production_bin' ],
      ['scripts/run_blastp_jobs.pl',                               'production_bin' ],      
      [ 'scripts/remove_snp_sites_with_missing_data',                'production_bin' ],
      [ 'scripts/plasmid_identification',                            'production_bin' ],
      [ 'scripts/identify_cluster_defining_snps',                    'production_bin' ],
      [ 'scripts/label_internal_nodes_of_newick_tree',               'production_bin' ],
      [ 'scripts/rnaexp2dnaplotter',                                 'production_bin' ],
      [ 'scripts/bigger_blast.pl',                                   'production_bin' ],
      [ 'scripts/flexi_blast.pl',                                    'production_bin' ],
      [ 'scripts/fasta_chunker.pl',                                  'production_bin' ],
      [ 'scripts/blast_formatter.pl',                                'production_bin' ],
      [ 'scripts/big_blast.pl',                                      'production_bin' ],
      [ 'scripts/sequenceformat.converter.pl',                       'production_bin' ],
      [ 'scripts/embl_to_ps.pl',                                     'production_bin' ],
      [ 'scripts/rfamscan2tab.pl',                                   'production_bin' ],
      [ 'scripts/tmhmm2embl.pl',                                     'production_bin' ],
      [ 'scripts/psu_union.pl',                                      'production_bin' ],
      [ 'scripts/signalp2embl.pl',                                   'production_bin' ],
      [ 'scripts/rfamscan_chado',                                    'production_bin' ],
      [ 'scripts/psu_splitter.pl',                                   'production_bin' ],
      [ 'scripts/split_fa.pl',                                       'production_bin' ],
      [ 'scripts/fasta_extractor.pl',                                'production_bin' ],
      [ 'scripts/dgpi_chado',                                        'production_bin' ],
      [ 'scripts/pfamscan2tab.pl',                                   'production_bin' ],
      [ 'scripts/annotations_update.pl',                             'production_bin' ],
      [ 'scripts/orthomcl_chado',                                    'production_bin' ],
      [ 'scripts/blast2tab.pl',                                      'production_bin' ],
      [ 'scripts/sequence_search.pl',                                'production_bin' ],
      [ 'scripts/omcl2genedb.pl',                                    'production_bin' ],
      [ 'modules/GoogleDocument.pm',                                 'production_lib' ],
      [ 'modules/GoogleDocumentHelper.pm',                           'production_lib' ],
      [ 'scripts/contigs2fas.pl',                                    'production_bin' ],
      [ 'scripts/shuffle_reads',                                     'production_bin' ],
      [ 'scripts/assemble_lanes',                                    'production_bin' ],
      [ 'scripts/map2bam.pl',                                        'production_bin' ],
      [ 'scripts/team133-bsub.pl',                                   'production_bin' ],
      [ 'modules/Pathfind.pm',                                       'production_lib' ],
      [ 'modules/PathfindLog.pm',                                    'production_lib' ],
      [ 'modules/FindLanes.pm',                                      'production_lib' ],
      [ 'modules/SubmissionLookup.pm',                               'production_lib' ],
      [ 'scripts/species_frequency',                                 'production_bin' ],
      [ 'scripts/stats_and_graphs_for_bams',                         'pathdev_bin' ],
      [ 'scripts/sh16_scripts_to_git.pl',                            'pathdev_bin' ],
      [ 'scripts/jit_scripts_to_git.pl',                             'pathdev_bin' ],
      [ 'scripts/fasta_one_line.pl',                                 'production_bin' ],
      [ 'scripts/list_species_sequenced.pl',                         'pathdev_bin' ],
      [ 'scripts/cshrc_to_bash.pl',                                  'pathdev_bin' ],
      [ 'scripts/select_gene_sequences.pl',                          'production_bin' ],
      [ 'scripts/get_GO_association.pl',                             'production_bin'],
      [ 'modules/DaemonsLog',                                        'production_lib' ],
      [ 'scripts/dotplot.pl',                                        'production_bin'],
      [ 'scripts/orthomcl2tab.pl',                                   'production_bin'],
      [ 'modules/Crawl',                                             'production_lib' ],
      [ 'scripts/pfamscan2tab_chado.pl',                             'production_bin'],
      [ 'scripts/find_untracked_studies.pl',                         'pathdev_bin' ],
      [ 'scripts/prosite_by_perl.pl',                                'production_bin' ],
      [ 'scripts/trna-se.pl',                                        'production_bin' ],
      [ 'scripts/rfamscan_dechunk.pl',                               'production_bin' ],
      [ 'scripts/run_beast.pl',                                      'production_bin' ],
      [ 'scripts/cogblast.pl',                                       'production_bin' ],
      [ 'scripts/reciprocal_fasta.pl',                               'production_bin' ],
      [ 'scripts/scout_wrapper.pl',                                  'production_bin' ],
      [ 'scripts/auto_update_go_terms.pl',                           'pathdev_bin' ],
      [ 'scripts/interpro_to_chado_load',                            'production_bin' ],
      [ 'scripts/generate_nctc_tab.pl',                              'pathdev_bin' ],
      [ 'scripts/filter_embl_with_essentiality.pl',                  'production_bin' ],
      [ 'scripts/transfer_genes.pl',                                 'production_bin' ],
      [ 'scripts/transfer_ids_to_EMBL.pl',                           'production_bin' ],
      [ 'scripts/extract_modifications_to_plots',                    'production_bin' ],
      [ 'scripts/get_library_type.pl',                               'production_bin' ],
      [ 'scripts/repeat_finder.pl',                                  'production_bin' ],
      [ 'scripts/het_snp_calculator.pl',                             'production_bin' ],
  ]

  java: [
        ["googlecode.jar",                                   "production_java"],
        ["src/GoogleDocument.class",                         "production_java"],
        ["src/GoogleDocumentHelper.class",                   "production_java"],
	["src/CATEGORY_DB.class",                            "production_java"],
	["src/GoogleDataProjectSlurper.class",               "production_java"],
	["src/GoogleReferenceProjectSlurper.class",          "production_java"],
	["src/Project.class",                                "production_java"],
	["src/Reference.class",                              "production_java"],
	["src/SearchSpreadsheet.class",                      "production_java"],
	["src/WriteConfigFiles.class",                       "production_java"],
  ]

  c: [
  ]

  lua: [
        [ "scripts/fixup_plasmodb",        "production_bin"],
        [ "scripts/fixup_tritrypdb",       "production_bin"],
        [ "scripts/add_products_to_fasta", "production_bin"],
  ]

  data: [
        [ 'adapters/solexa-adapters.fasta', 'production_etc' ],
        [ 'adapters/solexa-adapters.quasr', 'production_etc' ],
  ]

  shell: [
      [ 'scripts/sourmash',                           'production_bin'],
      [ 'scripts/genus_genbank_to_blast',             'pathdev_bin' ],
      [ 'scripts/refseq_blast_databases',             'pathdev_bin' ],
      [ 'scripts/update_tracking_databases.sh',       'pathdev_bin' ],
      [ 'scripts/wtsi_chado_privs.ksh',               'pathdev_bin' ],
      [ 'scripts/setup_pathpipe_environment.sh',      'pathdev_bin' ],
      [ 'scripts/setup_test_pathpipe_environment.sh', 'pathdev_bin' ],
      [ 'scripts/concatgff.sh',                       'pathdev_bin' ],
      [ 'scripts/tmhmm_chado',                        'production_bin' ],
      [ 'scripts/chado',                              'production_bin' ],
      [ 'scripts/writedb_entry',                      'production_bin' ],
      [ 'scripts/chado_dump_transcripts',             'production_bin' ],
      [ 'scripts/chado_dump_genome',                  'production_bin' ],
      [ 'scripts/art_act_launcher',                   'production_bin' ],
      [ 'scripts/tmhmm_chado',                        'production_bin' ],
      [ 'scripts/pfamscan_chado',                     'production_bin' ],
      [ 'scripts/chado_dump_proteins',                'production_bin' ],
      [ 'scripts/chado_dump_introns',                 'production_bin' ],
      [ 'scripts/pmid_extraction',                    'production_bin' ],
      [ 'scripts/dnaplotter',                         'production_bin' ],
      [ 'scripts/art',                                'production_bin' ],
      [ 'scripts/act',                                'production_bin' ],
      [ 'scripts/disk_usage_report.sh',               'pathdev_bin' ],
      [ 'scripts/directory_size_report.sh',           'pathdev_bin' ],
      [ 'scripts/backup_audit_schema.sh',             'pathdev_bin' ],
      [ 'scripts/generate_ref_index.sh',              'pathdev_bin' ],
      [ 'scripts/orientationtracker.sh',              'production_bin' ],
      [ 'scripts/chado_dump_proteins_ordered',        'production_bin' ],
      [ 'scripts/chado_dump_transcripts_coding',      'production_bin' ],
      [ 'scripts/chado_dump_transcripts_rna',         'production_bin' ],
      [ 'scripts/download-ci-web.sh',                 'pathdev_bin' ],
      [ 'scripts/download-www1.sh',                   'pathdev_bin' ],
      [ 'scripts/download-www2.sh',                   'pathdev_bin' ],
      [ 'scripts/download.sh',                        'pathdev_bin' ],
      [ 'scripts/profile.pathogen',                   'production_etc' ],
      [ 'scripts/cshrc.pathogen',                     'production_etc' ],
      [ 'scripts/ena_data_submission.conf',           'production_etc' ],
      [ 'scripts/elasticsearch-cluster-control',      'production_genedb' ],
      [ 'scripts/genedb-web-control',                 'production_genedb' ],
      [ 'scripts/hazelcast-cluster-control',          'production_genedb' ],
      [ 'scripts/omixed-web-control',                 'production_genedb' ],
      [ 'scripts/push-staging-to-snapshot2',          'production_genedb' ],
      [ 'scripts/copy_and_restart_genedb',            'production_genedb' ],
      [ 'scripts/fix-nightly',                        'production_genedb' ],
      [ 'scripts/fix-snapshot',                       'production_genedb' ],
      [ 'scripts/fix-staging',			      'production_genedb' ],
      [ 'scripts/db_info',			      'production_bin' ],
      [ 'scripts/run_jspecies',			      'production_bin' ],
      [ 'scripts/path-user-code-find.sh',	      'production_bin' ],
      [ 'scripts/chado_run_iprscan',		      'production_bin' ],
      [ 'scripts/chado_convert_load_iprscan',	      'production_bin' ],
      [ 'scripts/run_haploview',		      'production_bin' ],
      [ 'scripts/pinto_pathdb_environment_setup.sh',  'pathdev_bin' ],
      [ 'scripts/backup_midas_audit_logs.sh',         'pathdev_bin' ],
      [ 'scripts/orderedPainting',                    'production_bin'],
      [ 'scripts/phylosift',                          'production_bin' ],
      [ 'scripts/canu',                              'production_bin' ],
      [ 'scripts/01_unipaths',                        'production_bin' ],   
      [ 'scripts/02_qgraph',                          'production_bin' ],     
      [ 'scripts/03_clean',                           'production_bin' ],      
      [ 'scripts/04_patching',                        'production_bin' ],   
      [ 'scripts/05_simplify',                        'production_bin' ],   
      [ 'scripts/06_scaffolding',                     'production_bin' ],
      [ 'scripts/lcmlkin',                            'production_bin' ],
      [ 'scripts/rapmap',                             'production_bin' ],
      [ 'scripts/runMetaBat.sh',                      'production_bin' ],
      [ 'scripts/beast1.8',                           'production_bin' ],
      [ 'scripts/pf.conf',                            'production_etc' ],
      [ 'scripts/monitor_accounts_cron.sh',           'pathdev_bin'],
      [ 'scripts/filter_for_reago.sh',                'production_bin' ],
      [ 'scripts/mrbayes',                            'production_bin' ],
      [ 'scripts/recycle.py',                         'production_bin' ],
      [ 'scripts/pilon',                              'production_bin' ],
      [ 'scripts/atlas',                              'production_bin' ],
      [ 'scripts/genedb_dump_database_upload_to_ftp', 'production_bin' ],
      [ 'scripts/prepare_artemis_release.sh',         'pathdev_bin'],
      [ 'scripts/fc_run',                             'production_bin' ],
      [ 'scripts/shovill',                            'production_bin' ],
      [ 'scripts/strainphlan.py',                     'production_bin' ],
      [ 'scripts/Trinity',                            'production_bin' ],
      [ 'scripts/unicycler',                          'production_bin' ],
      [ 'scripts/tracer.conf',                          'production_bin' ]
  ]
  splimer: [ [ 'splimer.pl', 'production_bin' ], [ 'modules/FastaLength.pm', 'production_lib' ],
  ]
